cl-log-infrastructure/build.gradle.kts
cl-log-infrastructure/src/main/resources/application-dev.yml
cl-log-infrastructure/src/main/resources/application-local.yml

- p6spy 의존성을 추가합니다.
- 쿼리 로깅용입니다.
- `local` 프로필의 datasource 프로퍼티를 구성합니다.
- 추후 cloud config로 이전할 예정입니다.
- resolved #6

feat: p6spy 세팅 및 관련 의존성 추가

---

build.gradle.kts
cl-log-api/docs/example.http
cl-log-api/src/main/kotlin/org/depromeet/cllog/server/api/ClLogApplication.kt
cl-log-api/src/main/kotlin/org/depromeet/cllog/server/api/configuration/ApiConstants.kt
cl-log-api/src/main/kotlin/org/depromeet/cllog/server/api/configuration/ClogControllerAdvice.kt
cl-log-api/src/main/kotlin/org/depromeet/cllog/server/api/controller/ExampleController.kt
cl-log-domain/src/main/kotlin/org/depromeet/cllog/server/domain/.gitkeep
cl-log-domain/src/main/kotlin/org/depromeet/cllog/server/domain/common/ApiResponse.kt
cl-log-domain/src/main/kotlin/org/depromeet/cllog/server/domain/common/ClogException.kt
cl-log-domain/src/main/kotlin/org/depromeet/cllog/server/domain/common/ErrorCode.kt
cl-log-domain/src/main/kotlin/org/depromeet/cllog/server/domain/example/ExampleErrorCode.kt
cl-log-domain/src/main/kotlin/org/depromeet/cllog/server/domain/example/ExampleException.kt
cl-log-domain/src/main/kotlin/org/depromeet/cllog/server/domain/example/GetExample.kt
config/detekt.yml

- 공통 예외 구조를 세팅합니다.
- 각 클래스의 docs를 잘 읽어 보시고, `ClogException`, `ErrorCode`를 각 도메인 계층에서 상속/구현하여 활용해주세요.
- 서비스 영문명이 `Clog`로 확정되어, 관련 리팩토링이 진행될 예정입니다.
- 이번 PR부터 Clog로 사용하였으며, 곧 레포명 / 패키지명 / 모듈명 모두 수정할게요.
- resolved #9

feat: 공통 예외 구조 세팅

---

build.gradle.kts
cl-log-infrastructure/build.gradle.kts
cl-log-infrastructure/src/main/resources/application-local.yml

- kotlin jdsl 관련 의존성을 추가합니다.
- 왜 query dsl이 아닌 kotlin jdsl인지에 대해서는, [공식 문서](https://kotlin-jdsl.gitbook.io/docs/ko-1/jpql-with-kotlin-jdsl)를 참고해주세요.
- resolved #11

feat: Kotlin JDSL 관련 의존성 세팅

---

build.gradle.kts

- 코드 커버리지 측정을 위한 kover 세팅을 수행합니다.
- resolved #12

feat: kover 추가

---

build.gradle.kts
clog-api/Dockerfile

- 컨테이너 기반 배포를 위한 `Dockerfile`을 추가합니다.
-

feat: Dockerfile 추가

---

.github/workflows/dev-deploy.yml
clog-domain/build.gradle.kts
clog-infrastructure/build.gradle.kts
config/detekt.yml

- `dev` 환경 자동 배포 액션을 추가합니다.
- 신속 개발을 위해 `docker compose` 기반 세팅을 수행했으며, `live` 서버는 `k8s`로 구축 예정입니다.
- #15

feat: dev 환경 자동 배포 액션 추가

---

.github/workflows/dev-deploy.yml

- `dev-deploy.yml` 내 syntax error 발생 원인을 수정합니다.
- #15

fix: `dev-deploy.yml` syntax error 수정

---

clog-api/build.gradle.kts
clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/SwaggerConfiguration.kt
clog-api/src/main/resources/application-live.yml
clog-api/src/main/resources/application.yml

- `springdoc-openapi-starter-webmvc-ui` 의존성과 `SwaggerConfiguration`을 추가합니다.
- resolved #33

feat: swagger 관련 의존성 및 설정 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/SecurityConfig.kt

- swagger 및 auth 관련 path에 대한 permitAll 정책을 지정합니다.
- #39

feat: 스웨거 관련 paths permitAll 세팅

---

clog-api/build.gradle.kts

- 의존성이 두 번 들어가 스웨거 접속에 실패하던 이슈를 수정합니다 ;
- resolved #40

fix: swagger 관련 의존성 중복 이슈 해결

---

build.gradle.kts
clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/OAuth2LoginSuccessHandler.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/controller/AuthController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/SecurityConfig.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AppleAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/KakaoAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/infrastructure/UserRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserEntity.kt
config/detekt.yml

- `detekt`가 커밋 시마다 잘 작동하도록 수정합니다.
- 빌드 시마다 동작하지는 않도록, 제가 슬랙을 통해 드린 [**가이드**](https://depromeet16th.slack.com/archives/C087842JZ7F/p1740904701444189) 잘 확인해주십셔.
- detekt 적용으로 인해 코드 수정이 좀 있습니다.
- Supress로 눌러놓은건 꼭 잘 수정해주세요! @ghrltjdtprbs 
- resolved #48

fix: detekt 정상 동작하도록 수정

---

clog-api/build.gradle.kts
clog-api/src/main/resources/application-local.yml
clog-api/src/main/resources/application.yml

- health 체크 등등의 용도로 actuator를 추가합니다.
- 다른 용도가 생기면, 설정을 통해 각 엔드포인트의 노출 여부를 조정해주세요.
- resolved #37

feat: Spring Boot Actuator 추가

---

build.gradle.kts
clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/OAuth2LoginSuccessHandler.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/jwt/JwtFilter.kt

- `kotlin-logging` 라이브러리를 추가하고, 기존에 사용중이던 로거 클래스를 교체합니다.
- `JwtFilter`에서 로깅이 동작하지 않던 이슈를 수정합니다.
- `GenericFilterBean`의 `logger` property와 이름이 겹쳐 오작동한 듯 합니다.
- resolved #54

feat: kotlin-logging 라이브러리 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/ClogControllerAdvice.kt
clog-domain/build.gradle.kts
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/AuthService.kt

- Entity를 수정할 때엔, 반드시 Transaction이 설정되어 있어야 합니다.
- ClogControllerAdvice에 의해 에러 로그가 print되지 않던 이슈를 수정합니다.
- resolved #57

fix: AuthService 메서드에 트랜잭션이 걸려있지 않은 이슈 수정

---

clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Color.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/ColorRepository.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Coordinate.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Crag.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragColor.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragColorRepository.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/ColorEntity.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/ColorJpaRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CoordinateEntity.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragColorEntity.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragColorJpaRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragEntity.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragJpaRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragRepositoryAdapter.kt

- Crag 도메인 추가
- [SPS-79](https://depromeet-16-5.atlassian.net/browse/SPS-79?atlOrigin=eyJpIjoiM2QyYmFiYTM5YjBmNDljZjliYzA1N2RhMTQxNjJhMGEiLCJwIjoiaiJ9)
[SPS-79]: https://depromeet-16-5.atlassian.net/browse/SPS-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-79] Crag 도메인 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/controller/AuthController.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/AuthService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/LogoutService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/LocalLoginRequest.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AppleAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/KakaoAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/LocalAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/Provider.kt
clog-infrastructure/build.gradle.kts

- 로컬용 로그인 api 구현
- 서비스 클래스에 트랜잭션 일괄 추가

feature : 로컬용 로그인 로직 구현

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/presentation/AuthController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/UserContextResolver.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/jwt/JwtFilter.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/application/GetMe.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserController.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/LogoutService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/LoginDetails.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AppleAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/KakaoAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/LocalAuthProviderHandler.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/infrastructure/RefreshTokenRepository.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/application/UserService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/UserRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenJpaRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenRepositoryAdapter.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserJpaRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserRepositoryAdapter.kt

- [SPS-105](https://depromeet-16-5.atlassian.net/browse/SPS-105?atlOrigin=eyJpIjoiNGFhYWVmNzE3MTYwNDhlMDk4MDdiNWU3YjE5NWM4N2MiLCJwIjoiaiJ9)
[SPS-105]: https://depromeet-16-5.atlassian.net/browse/SPS-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat : 탈퇴 api 구현 및 UserContext 수정

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/presentation/AuthController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserController.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/application/UserService.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/application/dto/UpdateUserNameReauest.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/User.kt

- 로그인한 사용자의 이름을 변경
- [SPS-119](https://depromeet-16-5.atlassian.net/browse/SPS-119?atlOrigin=eyJpIjoiMDVjNmQwMDk1NmEyNGZjZWI4MThlMTg2NWQwYTE3MGQiLCJwIjoiaiJ9)
[SPS-119]: https://depromeet-16-5.atlassian.net/browse/SPS-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat : 이름 변경 api 구현

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/GetStorySummary.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StorySummaryResponse.kt

- 기록 종료 전, 기록에 대한 요약 정보를 제공해야 합니다. 해당 API를 구현합니다.
- [SPS-127](https://depromeet-16-5.atlassian.net/browse/SPS-127?atlOrigin=eyJpIjoiNWQ3ODQ1M2MwZWU4NGFkMzlhMDhlZTEwNjI2ZDBmMzIiLCJwIjoiaiJ9)
[SPS-127]: https://depromeet-16-5.atlassian.net/browse/SPS-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 기록 요약 정보 조회 API 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/SwaggerConfiguration.kt

Swagger https 프로토콜 설정

---

clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/NcpObjectStorageClient.kt

fix : 썸네일 이미지를 공개로 업로드

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/UpdateStoryMemo.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryQueryController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/UpdateStoryMemoRequest.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/domain/ForbiddenException.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ErrorCode.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryNotFoundException.kt

- 놀랍게도 메모도 수정할 수 있습니다.
- [[SPS-145](https://depromeet-16-5.atlassian.net/browse/SPS-145)]
[SPS-145]: https://depromeet-16-5.atlassian.net/browse/SPS-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-145] 기록 메모 수정 API 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/CalendarResponse.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/GetCalendar.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/controller/CalendarController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/controller/CalendarQuery.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/Attempt.kt

- 시도 횟수 관련 필드를 추가합니다.
- `calender` -> `calendar` 오타 수정합니다 ㅎㅎ;
- [[SPS-150](https://depromeet-16-5.atlassian.net/browse/SPS-150)] 
[SPS-150]: https://depromeet-16-5.atlassian.net/browse/SPS-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-150] 캘린더 조회 API 내 시도 횟수 필드 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/DeleteStory.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryController.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/Story.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryEntity.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryJpaRepository.kt

- 스토리 삭제 API 추가
- [SPS-146](https://depromeet-16-5.atlassian.net/browse/SPS-146?atlOrigin=eyJpIjoiNWUyMTRmZmFjZjVmNDIxOThmZTNhNTlkZWQ2MjQyOTMiLCJwIjoiaiJ9)
[SPS-146]: https://depromeet-16-5.atlassian.net/browse/SPS-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-146] story 삭제 API 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/CalendarResponse.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/GetCalendar.kt

- 클라이언트와 상의 끝에, 깔끔한 DTO를 만들기 위한 노력을 하기로 결정했습니다.
- [[SPS-150](https://depromeet-16-5.atlassian.net/browse/SPS-150)]
[SPS-150]: https://depromeet-16-5.atlassian.net/browse/SPS-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-150] 캘린더 조회 API 내 월 별 요약 정보 한 필드로 정리

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/application/GetMyCrag.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/presentation/CragQueryController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/application/GetMyGrade.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/GradeQueryController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/dto/GetMyGradeInfoResponse.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/dto/GradeExtensions.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryAdapter.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryJpaRepository.kt

- 내 기록의 난이도 조회 api 구현
- 기존 암장조회와 동일한 구조로 구현하였습니다.
- [SPS-148](https://depromeet-16-5.atlassian.net/browse/SPS-148?atlOrigin=eyJpIjoiY2JlZWU5ZDA2NDc2NDE0MDg5MzNiMjljNTY4NDdiOTciLCJwIjoiaiJ9)
[SPS-148]: https://depromeet-16-5.atlassian.net/browse/SPS-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-148] 내 난이도 조회 API 구현

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/thumbnail/presentation/ThumbnailController.kt

fix : @RequestTParam -> @RequestPart

---

clog-api/src/main/resources/application.yml

- 썸네일 업로드 테스트 때문에 50MB로 지정했습니다.

fix : 파일 업로드 용량 임의로 증량

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/presentation/CragQueryController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/GradeQueryController.kt
clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/utils/dto/CursorPagination.kt

- request cursor parameter 타입 명시적 선언
-

[Fix] Request cursor parameter 타입 명시적 선언

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptDetailResponse.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/AttemptQuery.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/AttemptMapper.kt

API: /api/v1/attempts/{attemptId}
- 응답 필드 추가 (year, month)
``` json
---------- 변경 전
{
"data": {
"storyId": 1,
"problemId": 1,
"color": {
"id": 1,
"name": "노랑",
"hex": "#FF0000"
},
}
---------- 변경 후
{
"data": {
"story": {
"createdAt": "2025-03-23T01:19:00",
"problemId": 1,
...
}
```
-

[Refactor] 시도 상세 조회 API 응답 필드 추가

---

clog-infrastructure/src/main/resources/infrastructure/application-dev.yml
clog-infrastructure/src/main/resources/infrastructure/application.yml

- dev 환경을 제외하면, ddl-auto가 validate로 설정되도록 합니다.
- Jpa Entity와 스키마 안맞으면 애플리케이션 못킵니당.
- [[SPS-181](https://depromeet-16-5.atlassian.net/browse/SPS-181)]
[SPS-181]: https://depromeet-16-5.atlassian.net/browse/SPS-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-181] `ddl-auto: validate` 설정

---

.github/workflows/prod-deploy.yml

- 이미지 태그가 제대로 구성되지 않는 이슈를 수정합니다.
-

[SPS-178] 운영 배포 액션 오류 수정

---

clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/ProblemMapper.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/StoryMapper.kt

- 암장, 난이도 등 nullable한 필드 변환에 대한 대응을 추가합니다.
-

fix: Mapper를 통한 변환 시, nullable 필드가 고려되지 않은 이슈 수정

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/GetCalendar.kt

- 별개로.. 캘린더 API 제대로 리팩토링 한 번 해야겠습니다..
-

fix: Calender API 조회 시, grade nullable이 고려되지 않은 이슈 수정

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/CalendarResponse.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/GetCalendar.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/problem/ProblemQuery.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryQuery.kt
clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/utils/.gitkeep
clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/utils/Constants.kt

- 팩터리 메서드를 적극 활용하여 코드를 깔꼼하게 변경합니다..
- [[SPS-185](https://depromeet-16-5.atlassian.net/browse/SPS-185)]
[SPS-185]: https://depromeet-16-5.atlassian.net/browse/SPS-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-185] 캘린더 조회 API 리팩토링

---

.github/workflows/dev-deploy.yml

- 슈퍼샤이 팀의 궁핍한 지갑 사정을 고려하여.. 개발 서버에 admin을 띄우지 않습니다.
- 곧 prod 액션에 추가할게요.
-

refactor: 개발 환경 배포 액션에서 admin 제거

---

.github/workflows/prod-deploy.yml
clog-admin/build.gradle.kts
clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/common/config/SecurityConfig.kt
clog-admin/src/main/resources/application.yml

- prod deploy action에 admin 관련 내용을 추가합니다.
- admin 모듈에 actuator를 추가합니다.
- [[SPS-194](https://depromeet-16-5.atlassian.net/browse/SPS-194)]
[SPS-194]: https://depromeet-16-5.atlassian.net/browse/SPS-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-194] Admin 운영 배포를 위한 action 수정 및 actuator 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/application/GetNearByCrag.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragAdapter.kt

- [] 버그 수정
- 페이지 마지막 요소가 다음 페이지 첫 번째 요소에도 포함되는 중복 조회 수정
-

가까운 암장 중복 조회 수정

---

clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/crag/application/SaveCrag.kt

fix: 빌드 오류 수정

---

clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Crag.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragStatus.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragAdapter.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragEntity.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/CragMapper.kt
clog-infrastructure/src/main/resources/infrastructure/db/migration/V3__add_crag_status.sql

- 아래와 같은 경우를 대비하여 암장 상태를 추가합니다.
- 폐업
- 잘못된 암장 정보
-

feat: 암장 상태 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/application/GetNearByCrag.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/presentation/CragQueryController.kt
clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/utils/dto/CoordinateRequest.kt

- 요청 위치 정보가 null 일 시 기본 값 설정
-

위치 정보 기본 값 설정

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryResponse.kt

- 기록 종료 화면에서 총 운동 시간이 보여져야 합니다.
-

feat: 기록 상세 조회 API -> 총 운동 시간 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptFolderViewExtensions.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptVideoResponse.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/SaveVideoRequest.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/VideoResponse.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/video/VideoCommand.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/video/VideoQuery.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/VideoMapper.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoEntity.kt
clog-infrastructure/src/main/resources/infrastructure/db/migration/V4__add_crag_status.sql

- thumbnail_url이 null이면 클라이언트에서 기본 이미지로 나타내줍니다.
-

feat: thumbnail_url nullable로 변경

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptDetailResponse.kt

refactor: 시도 상세 조회 API -> id 필드 추가

---

.github/workflows/dev-deploy.yml

- 수동 트리거좀 하면서 테스트 진행하려 합니다..!
-

feat: dev 액션에 workflow_dispatch 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/GetStorySummary.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StorySummaryResponse.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/ProblemMapper.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/StoryMapper.kt
clog-infrastructure/src/main/resources/infrastructure/db/migration/V1__init.sql

refactor : StoryThumbnailUrl에 응답값 추가

---

.github/workflows/dev-deploy.yml
.github/workflows/prod-deploy.yml

- dev SSH 인증 방식을 `password` -> `key`로 변경합니다.
- dev, main 배포 단계를 `빌드` -> `배포`로 세분화합니다.
-

fix: dev 배포 액션 실패 현상 수정

---

.github/workflows/dev-deploy.yml
.github/workflows/prod-deploy.yml

feat: 액션에 environment 추가

---

.github/workflows/dev-deploy.yml
.github/workflows/prod-deploy.yml

feat: dev 액션 compose 파일 경로 변경 (이번엔 진짜 됨)

---

clog-api/Dockerfile

- 운영 서버 API가 느리다는 제보가 속속들이 들어오고 있습니다 (...)
- 빠른 수정을 위해, 트랜잭션 성능 분석에 용이한 elastic-apm을 후딱 도입합니다.
-

feat: Elastic APM 추가

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/TokenService.kt

fix: refresh token claim 추출 시, Bearer prefix 제거

---

clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/VideoMapper.kt

fix: 영상 조회 시, timeMs 기준으로 타임스탬프 정렬하도록 변경

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/ApiConstants.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/UserContextResolver.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/SaveStory.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/SaveStoryRequest.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryCommandController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/UserContext.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/AppVersion.kt

- `AppVersion` 클래스를 추가합니다.
- 버전에 대한 대소 비교가 가능합니다.
- `x.x.x` 형태로 값을 강제합니다.
- `UserContext`에 `AppVersion`을 추가합니다.
- 필요하면 자유롭게 뽑아 쓰세요.
- [[SPS-290](https://depromeet-16-5.atlassian.net/browse/SPS-290)]
[SPS-290]: https://depromeet-16-5.atlassian.net/browse/SPS-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-290] `AppVersion` class 추가 및 `UserContext`에 탑재

---

clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragAdapter.kt

refactor: 가까운 암장 조회 시, 난이도 fetch join 수행되도록 수정

---

clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragAdapter.kt

fix: 난이도 없는 암장 조회 안되는 이슈 수정

---

clog-api/src/main/resources/logback.xml

- 콘솔 로그 패턴과 로그 스태이시는 영향을 주지 않고 별개로 동작..
-

콘솔 로그 패턴 변경(logback 수정)

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/application/UpdateUser.kt

[PLT-9] validation 수정

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/application/UpdateUser.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserResponse.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/User.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserEntity.kt

[PLT-9] 키, 팔길이 double로 변경

---

.github/workflows/prod-deploy.yml
clog-api/src/main/resources/logback-spring.xml

chore: 인프라 AWS 이전에 따른 prod 배포 액션 수정

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/SaveGalleryStoryRequest.kt

- 암장건너뛰기 기능이 있어 요청값에 cragId를 nullable로 변경했습니다.

fix : crag 요청을 nullable로 수정

---

clog-api/src/main/kotlin/org/depromeet/clog/server/api/fcm/application/SaveFcmToken.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/fcm/presentation/FcmTokenCommandController.kt
clog-api/src/main/kotlin/org/depromeet/clog/server/api/fcm/presentation/SaveFcmTokenRequest.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/fcm/FcmTokenRepository.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/fcm/SaveFcmTokenCommand.kt
clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/notification/NotificationType.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/fcm/FcmTokenAdapter.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/fcm/FcmTokenEntity.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/fcm/FcmTokenJpaRepository.kt
clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/notification/NotificationEntity.kt

- FcmTokenEntity 추가
- NotificationEntity 추가
- 앱 실행 시 토큰 갱신할 수 있도록 api 구현
- 동일 userId는 token,device 칼럼 update
- #182

feat : FCM 토큰 저장 API 구현 및 관련 엔티티 추가
