depromeet/clog-server

- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/User.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/common/BaseEntity.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserEntity.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserJpaRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserRepositoryAdapter.kt
- `BaseEntity`를 추가합니다.
- `spring-boot-starter-data-jpa` dependency를 참조해야 하므로, `infrastructure` 모듈에 존재해야 합니다.
- but, Jpa Entity가 `domain` 모듈에 있어 상속이 불가능합니다.
- 따라서, 자연스럽게 Jpa Entity를 `infrastructure` 모듈로 옮기고, `domain` 계층에선 pojo를 사용하게 됩니다.
- 멀티 모듈의 순기능! (순기능 맞겠죠?)
- resolved #44
> feat: BaseEntity 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/controller/AuthController.kt
- clog-api/src/main/resources/application.yml
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/AuthService.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/KakaoLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AppleAuthProviderHandler.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AuthProviderHandler.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/KakaoAuthProviderHandler.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/domain/RefreshToken.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/infrastructure/RefreshTokenRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenEntity.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenJpaRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenRepositoryAdapter.kt
- 프론트 요청사항으로 카카오 로그인만 authorization code를 넘겨받는 방식에서 idToken을 직접 넘겨받는 방식으로 수정했습니다.
- IdToken을 바로 넘겨받는 방식은 보안상 매우 안좋으므로 이 방식은 추후에 프론트와 합의하겠습니다.
- refreshToken 저장시에 "Bareer"도 같이 저장되는 부분 수정하였습니다.
- refreshToken엔티티를 infra모듈로 이동하였습니다.
- Provider별 인증 로직 분리 및 전략 패턴 적용
- refreshToken의 loginId의 중복 가능성을 고려해 userId를 사용하도록 추가
> refactor : 프론트 요청으로 카카오 로그인을 idToken 전달받는 방식으로 수정

- build.gradle.kts
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/presentation/AuthController.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/AuthService.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/KakaoLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/LocalLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/AppleLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/KakaoLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/LocalLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/RefreshTokenRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/response/AuthResponseDto.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AppleAuthProviderHandler.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AuthProviderHandler.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/KakaoAuthProviderHandler.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/LocalAuthProviderHandler.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/application/UserService.kt
- 액세스토큰 만료시 리프레쉬토큰으로 액세스토큰 재발하는 api 추가
- 액세스토큰 재발급 받으면서 리프레쉬토큰도 갱신
- dto를 request/response로 분리
- [SPS-118](https://depromeet-16-5.atlassian.net/browse/SPS-118?atlOrigin=eyJpIjoiOWRlOTdmNTNiNTI2NDM1ZTk3NDdiYzU1YjM1OWU4MDAiLCJwIjoiaiJ9)
[SPS-118]: https://depromeet-16-5.atlassian.net/browse/SPS-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat : 액세스토큰 재발급 api 구현

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/SaveAttempt.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/VideoRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/SaveStory.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/SaveStoryRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/video/VideoStampRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoStampAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoStampJpaRepository.kt
- 시도를 저장하는 API를 추가합니다.
- [SPS-123](https://depromeet-16-5.atlassian.net/browse/SPS-123?atlOrigin=eyJpIjoiM2U2ZDc5OTQzNjlhNDI3N2E0ZjVkNTI0NjA2YWNiOWQiLCJwIjoiaiJ9)
[SPS-123]: https://depromeet-16-5.atlassian.net/browse/SPS-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 시도 저장 API 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/application/SaveProblem.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/presentation/ProblemController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/presentation/ProblemResponse.kt
- 다음 문제 버튼 클릭 시, 문제 정보를 저장하는 API를 추가합니다.
- [SPS-125](https://depromeet-16-5.atlassian.net/browse/SPS-125?atlOrigin=eyJpIjoiMDQ4MTU0MWE3ZTkyNDhlN2FiNmI5NTk1MmVjMTVlOTUiLCJwIjoiaiJ9)
[SPS-125]: https://depromeet-16-5.atlassian.net/browse/SPS-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 문제 저장 API 추가

- clog-api/build.gradle.kts
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/SaveAttempt.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/GradeResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/SaveAttemptResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/VideoResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/VideoStampResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/application/SaveProblem.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/presentation/ProblemController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/presentation/ProblemResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/presentation/SaveProblemResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/GetStory.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/SaveStory.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/Attempt.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/problem/Problem.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/Story.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryRepository.kt
- clog-infrastructure/build.gradle.kts
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptEntity.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptJpaRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/problem/ProblemEntity.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/problem/ProblemJpaRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryEntity.kt
- 기록 정보를 조회하기 위해, Aggregation하는 로직과 API를 추가합니다.
- [SPS-126](https://depromeet-16-5.atlassian.net/browse/SPS-126?atlOrigin=eyJpIjoiMGY5Njk4Nzk0YjMwNDQ1YTg2YjIzNDBmYTY5Y2M3NWQiLCJwIjoiaiJ9)
[SPS-126]: https://depromeet-16-5.atlassian.net/browse/SPS-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 기록 정보 조회 API 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/calender/application/GetCalender.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/calender/controller/CalenderController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/calender/controller/CalenderQuery.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/calender/Calender.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/calender/CalenderRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/calender/CalenderAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryJpaRepository.kt
- 캘린더 메인 화면 조회에 사용되는 API를 구현합니다.
- resolved [[SPS-136](https://depromeet-16-5.atlassian.net/browse/SPS-136?atlOrigin=eyJpIjoiMWQ2Y2RmZDg2YzBlNDg4M2ExNWZkMGU3YmNmYmQyMWYiLCJwIjoiaiJ9)]
[SPS-136]: https://depromeet-16-5.atlassian.net/browse/SPS-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 캘린더 메인 조회 API 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/UpdateAttemptAndParents.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptUpdateController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptUpdateRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/StampRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/presentation/ProblemController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/video/application/UpdateVideo.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/video/presentation/VideoController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/video/presentation/VideoUpdateRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/AttemptNotFoundException.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/AttemptRepository.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ErrorCode.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/problem/ProblemRepository.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/video/VideoNotFoundException.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/video/VideoRepository.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/video/VideoStampRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/GradeEntity.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/problem/ProblemAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoStampAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoStampJpaRepository.kt
- 영상 정보 수정 시 사용될 API들을 추가합니다.
- resolved [[SPS-138](https://depromeet-16-5.atlassian.net/browse/SPS-138?atlOrigin=eyJpIjoiZDlhOTBhOWRhNGYwNDNlZWE2NjhhNTY3NzAzYzA4ZDUiLCJwIjoiaiJ9)]
[SPS-138]: https://depromeet-16-5.atlassian.net/browse/SPS-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-138] 영상 및 시도 정보 수정 API 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/DeleteAttemptAndParents.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/SaveAttempt.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/UpdateAttemptAndParents.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptCommandController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/SaveAttemptResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptUpdateRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/GradeResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/SaveAttemptResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/StampRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/VideoRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/VideoResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/VideoStampResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/problem/presentation/ProblemResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/SaveStoryRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/video/presentation/VideoUpdateRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/AttemptRepository.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/problem/ProblemRepository.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/problem/ProblemAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryAdapter.kt
- 영상 삭제 API를 추가합니다.
- 만약 영상의 부모인 문제, 기록의 자식들이 모두 지워졌다면 해당 부모도 삭제합니다.
- [[SPS-139](https://depromeet-16-5.atlassian.net/browse/SPS-139)]
[SPS-139]: https://depromeet-16-5.atlassian.net/browse/SPS-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-139] 시도 삭제 API 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/GetAttempt.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptQueryController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptFilter.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptFilterRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptFolderViewExtensions.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptVideoResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/GetAttemptDetailResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/GetAttemptResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/AttemptRepository.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/dto/AttemptFilter.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/dto/AttemptFolderView.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptJpaRepository.kt
- 나의 클라이밍 기록 조회
- gradeId, cragId, attemptStatus로 필터링 가능
- [SPS-148](https://depromeet-16-5.atlassian.net/browse/SPS-148?atlOrigin=eyJpIjoiY2JlZWU5ZDA2NDc2NDE0MDg5MzNiMjljNTY4NDdiOTciLCJwIjoiaiJ9)
[SPS-148]: https://depromeet-16-5.atlassian.net/browse/SPS-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-148] 폴더(나의 클라이밍 기록) 조회 API 구현

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptFolderViewExtensions.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/GetAttemptDetailResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/dto/AttemptFolderView.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptJpaRepository.kt
- 폴더 API에 암장 주소가 빠져서, 추가합니다.
- 넣는 김에, 기존에 있던 `CragResponse`와 `ColorResponse`를 재활용하도록 수정합니다.
- [[SPS-164](https://depromeet-16-5.atlassian.net/browse/SPS-164)]
[SPS-164]: https://depromeet-16-5.atlassian.net/browse/SPS-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-164] 폴더 API 응답 내 crag, color response 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserController.kt
- clog-api/src/main/resources/application.yml
- 액세스 토큰 유효시간을 : 1시간 -> 24시간으로 변경하였습니다.
- 리프레쉬 토큰 7일 / 액세스토큰 24시간
> refactor : 액세스토큰 만료시간 조정

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/application/GetCragGrade.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/GradeQueryController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/dto/GetGradeResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/dto/GradesResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/grade/GradeRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/GradeAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/GradeJpaRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/RegionAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/ThumbnailAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserAdapter.kt
- 암장에 포함된 난이도 조회 API 추가
``` json
{
"data": {
"grades": [
{
"gradeId": 1,
"order": 1,
"color": {
"id": 8,
"name": "#A50021",
"hex": "테스트 레드"
}
},
{
"gradeId": 2,
"order": 2,
"color": {
"id": 9,
"name": "#D99058",
"hex": "테스트 오렌지"
}
},
{
"gradeId": 3,
"order": 3,
"color": {
"id": 10,
"name": "#E3A857",
"hex": "테스트 옐로우"
}
},
{
"gradeId": 4,
"order": 4,
"color": {
"id": 11,
"name": "#609078",
"hex": "테스트 비리디"
}
}
]
}
}
```
- [SPS-167](https://depromeet-16-5.atlassian.net/browse/SPS-167?atlOrigin=eyJpIjoiNjE2ZTA1OGI0MWE0NDA0ODhkYWQzNDEzZjkyMzE4MTEiLCJwIjoiaiJ9)
[SPS-167]: https://depromeet-16-5.atlassian.net/browse/SPS-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-167] 암장 난이도 조회 API 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/ClogControllerAdvice.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/ClogAuthenticationEntryPoint.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/SecurityConfig.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ErrorCode.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ErrorResponse.kt
- `AuthenticationEntryPoint`를 재정의하지 않아, 모든 `Exception`에 대해 `403`이 발생하는 이슈를 수정합니다.
- 모든 `Exception`에 대해, Spring boot default exception body가 아닌 `ClogErrorResponse`가 반환되도록 수정합니다.
- 클라이언트에서 잘못된 입력을 시도했을 때, 상세한 `ErrorResponse`가 반환되도록 수정합니다.
- [[SPS-175](https://depromeet-16-5.atlassian.net/browse/SPS-175)]
[SPS-175]: https://depromeet-16-5.atlassian.net/browse/SPS-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-175] Exception Handling 상세화 및 AuthenticationEntryPoint 커스터마이징

- clog-api/build.gradle.kts
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/AuthService.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/LogoutService.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/TokenService.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/AppleUserInfo.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/KakaoUserInfo.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/LoginDetails.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/request/AppleLoginRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/request/KakaoLoginRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/request/LocalLoginRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/request/RefreshTokenRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/dto/response/AuthResponseDto.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/AppleAuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/AuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/KakaoAuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/LocalAuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/presentation/AuthController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/UserContextResolver.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/jwt/JwtFilter.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/application/AppleUserDeletionService.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/application/UserService.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserController.kt
- clog-domain/build.gradle.kts
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/KakaoLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/LocalLoginRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/RefreshTokenRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AuthProviderHandler.kt
- auth 관련 application 계층을 api 모듈로 이전합니다.
- auth 관련 의존성과 환경변수가 domain 계층에 위치함으로써, admin 모듈이 auth 관련 의존성을 가지게 됩니다.
- 즉, auth 관련 설정값이 admin 모듈에도 세팅되어야 하는 현상이 발생합니다.
- [[SPS-176](https://depromeet-16-5.atlassian.net/browse/SPS-176)]
[SPS-176]: https://depromeet-16-5.atlassian.net/browse/SPS-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-176] Auth 관련 의존성 API 모듈로 이전

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/ClogApplication.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/ClogControllerAdvice.kt
- clog-api/src/main/resources/application.yml
- k8s Deployment의 liveness / readiness probe를 적용하기 위해 actuator 설정을 변경합니다.
- 서버 타임존 설정을 추가합니다.
- [[SPS-180](https://depromeet-16-5.atlassian.net/browse/SPS-180)]
[SPS-180]: https://depromeet-16-5.atlassian.net/browse/SPS-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-180] liveness/readiness health check 추가

- .github/workflows/prod-deploy.yml
- main 브랜치 push 시, 운영 서버 업데이트가 수행되도록 세팅합니다.
1. 기존과 동일하게 gradle build 후 docker image build & push를 수행합니다.
- 이 때, 이미지 태그는 github run number(고유한 시퀀스) + commit sha 8자리입니다.
2. [private k8s Manifests 레포지토리](https://github.com/clog-depromeet/clog-server-argocd-manifests)에 이미지 태그를 업데이트 해줍니다.
3. ArgoCD가 해당 레포지토리의 변경 사항을 감지하고, 자동으로 싱크 및 배포를 수행해줍니다.
- [[SPS-178](https://depromeet-16-5.atlassian.net/browse/SPS-178)]
[SPS-178]: https://depromeet-16-5.atlassian.net/browse/SPS-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-178] k8s manifests 레포지토리 연동을 통한 운영 서버 자동 배포 액션 추가

- .github/workflows/dev-deploy.yml
- clog-admin/Dockerfile
- clog-admin/build.gradle.kts
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/ClogAdminApplication.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/application/AdminService.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/presentation/AdminController.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/presentation/dto/ColorResult.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/presentation/dto/CragResult.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/presentation/dto/GradeResult.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/presentation/dto/SaveCrag.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/presentation/dto/SaveCragColor.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/api/presentation/dto/SaveCragGrade.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/common/AdminUserDetailsService.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/common/config/SecurityConfig.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/domain/crag/ColorAdminRepository.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/domain/crag/CragAdminRepository.kt
- clog-admin/src/main/kotlin/org/depromeet/clog/server/admin/domain/crag/GradeAdminRepository.kt
- clog-admin/src/main/resources/application.yml
- clog-admin/src/main/resources/templates/admin/colorList.html
- clog-admin/src/main/resources/templates/admin/cragDetails.html
- clog-admin/src/main/resources/templates/admin/cragList.html
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/ClogApplication.kt
- clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/properties/KakaoMapProperties.kt
- clog-infrastructure/build.gradle.kts
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/admin/ColorAdminAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/admin/CragAdminAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/admin/GradeAdminAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/ColorJpaRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/GradeJpaRepository.kt
- 관리자 API 추가 (암장 생성, 색상 생성, 난이도 생성 및 조회)
<div style="display: flex; flex-wrap: wrap; justify-content: space-between;">
</div>
- [SPS-121](https://depromeet-16-5.atlassian.net/browse/SPS-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[SPS-121]: https://depromeet-16-5.atlassian.net/browse/SPS-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-121] 어드민 API 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/AppleAuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/KakaoAuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/LocalAuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/application/GetReport.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/presentation/dto/ReportResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/User.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserEntity.kt
- 최초 가입 시, `user.name`을 `null`로 세팅합니다.
- `users/me` 조회 시, `name`이 `null`이면 클라이언트에서 닉네임 설정 플로우를 전개합니다.
- [[SPS-217](https://depromeet-16-5.atlassian.net/browse/SPS-217)]
[SPS-217]: https://depromeet-16-5.atlassian.net/browse/SPS-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-217] 최초 가입 시, `user.name`이 null로 세팅되도록 수정

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/calendar/application/CalendarResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryQuery.kt
- 그렇습니다.. 사실 기록 별로도 썸네일이 필요했었는데, 까먹었습니다.
-
> refactor: 캘린더 조회 시, 기록 별 썸네일 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/application/strategy/AppleAuthProviderHandler.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/application/AppleUserDeletionService.kt
- 애플 revoke 요청 시, `authorization_code`가 아닌 `refresh_token`을 넘기도록 (급하게) 수정합니다.
-
> fix: 애플 계정 회원 탈퇴 시, authorization_code가 아닌 refresh_token을 전달하도록 수정

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/ApiConstants.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/SaveStory.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/SaveStoryRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/StoryCommandController.kt
- 앱 버전 1.0.2 이하에서는 StoryStatus에 대한 대응을 할 수 없습니다.
- 따라서, 무조건 DONE으로 저장합니다.
-
> feat: `APP_VERSION` 헤더에 따라 story status 다르게 저장

- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/ImageCropper.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/NcpObjectStorageClient.kt
- clog-infrastructure/src/main/resources/infrastructure/application.yml
- 썸네일이 png 타입인 경우, 이미지를 1:1 비율로 자릅니다.
- 지금 썸네일이 찌부된 상태로 나와, 앱 완성도가 낮아보이기 때문에 조치해둡니다.
- 다만, 이미지를 메모리에 적재한 후 수행하기 때문에 리소스 사용량이 많이 늘어날 수 있습니다.
- 클라리언트에서 찌부 현상 해결해주면, 바로 없애야 합니다..!
- [[SPS-279](https://depromeet-16-5.atlassian.net/browse/SPS-279)]
[SPS-279]: https://depromeet-16-5.atlassian.net/browse/SPS-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-279] 썸네일 이미지 1:1 비율로 자르는 기능 임시 추가

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/thumbnail/presentation/ThumbnailController.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/thumbnail/application/ThumbnailPresignedService.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/thumbnail/dto/ThumbnailPresignedUploadRequest.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/thumbnail/dto/ThumbnailPresignedUploadResponse.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/ncp/NcpObjectStorageClient.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/ncp/ThumbnailServiceImpl.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/s3/AwsS3PresignedClient.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/s3/ThumbnailPresignedServiceImpl.kt
- clog-infrastructure/src/main/resources/infrastructure/application.yml
- 썸네일 업로드가 너무 느려 최적화하였습니다.
- **서버를 거치지 않고 클라이언트에서 직접 S3에 이미지 업로드**를 하는 구조고, **CloudFront로 빠른 이미지 제공**, 그리고 **서버는 presigned URL 발급만 담당**하는 방식으로 변경되었습니다.
- 클라이언트 측에서 S3측으로 이미지 업로드를 수행해야해서 별도 안내 필요합니다.(노션으로 공유 예정)
> refactor : 썸네일 업로드 최적화

- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryAdapter.kt
- 서브쿼리 쓰기 싫은데.. 우선 이렇게 픽스합니다.
- `attempt_id` 기반으로 `story`를 조회할 때, where 조건을 `attempt_id`로 지정하면 해당 attempt와 problem에 대항하는 row만 가져옵니다..
- 저희가 원하는 동작은 해당 `attempt`가 속하는 `story`의 `problem`과 `attempt`를 모두 가져오는 것이므로, `story_id`를 먼저 구하고 where 조건을 `story_id`에 걸어두는 것으로 수정합니다.
- [SPS-299](https://depromeet-16-5.atlassian.net/browse/SPS-299)
[SPS-299]: https://depromeet-16-5.atlassian.net/browse/SPS-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SPS-299] 특정 attempt 삭제 안되는 이슈 수정

- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryAdapter.kt
- clog-infrastructure/src/main/resources/infrastructure/application.yml
- `hibernate.default_batch_fetch_size`를 적용하여, in절을 사용해 자식들을 가져오도록 세팅합니다.
- `problems` 정도는 fetch join 하도록 수정합니다.
-
> refactor: 캘린더 조회 쿼리 개선

- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragAdapter.kt
```
firstResult/maxResults specified with collection fetch; applying in memory
```
- 굉장히 익숙한 warn 로그가..
- `hibernate.default_batch_fetch_size`가 in절로 조회 때려줄테니.. fetch join을 그냥 빼버립시당
-
> refactor: 내 주변 암장 조회 쿼리 내 fetchJoin 제거

- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/ColorJpaRepository.kt
- 문제 정의 : dev 환경에서 /crags/me 에러
- 원인 : DISTINCT와 ORDER BY(g.id)가 함께 사용되면서 MySQL 8.0 이상에서 "Expression not in SELECT list" 오류가 발생.(dev는 MySQL 9.2.0)
- 해결 : GROUP BY + ORDER BY MAX(...)로 구조 변경하여 호환성 확보.
> fix: MySQL 9.2.0 에서 DISTINCT + ORDER BY 오류 발생 문제 해결

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/SaveGalleryStory.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/GalleryStoryCommandController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/SaveGalleryStoryRequest.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/presentation/SaveGalleryStoryResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/AttemptStatus.kt
- clog-infrastructure/src/main/resources/infrastructure/db/migration/V8__alter_attempt_status_default.sql
1. `Story` 생성
2. `Problem` 연결 및 저장
3. `Video` 개수만큼 `Attempt` 자동 생성 (1:1 연결)
4. 각 `Video` 저장
- 추가 작업:
- `Attempt.status` 컬럼에 `UNKNOWN` enum 값을 추가했습니다.
- 갤러리 영상 묶음 기록 등록 시 사용자로부터 `status`(예: 성공/실패) 값을 받지 않으므로,  `UNKNOWN`을 저장합니다.
- 후속적으로 `attempt.status`는 영상 검토 또는 사용자 입력에 따라 변경될 수 있습니다.
- 기획에 따라 사용자는 단순 영상 업로드만 수행하고, 시도 결과는 별도로 입력하지 않도록 구현되어 있습니다.
- 따라서 최초 insert 시에는 `UNKNOWN`으로 통일 저장하고, 등록 후 수정에서 `SUCCESS`, `FAILURE` 등으로 갱신해야합니다.
- 문제 난이도 또한 등록 후 수정에서 갱신합니다.
-----
> feat : 갤러리 영상 묶음 기록 등록 api 구현

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/story/application/SaveGalleryStory.kt
- story 등록하자마자 외부 노출되도록 변경 요청
-> 갤러리 영상 묶음 기록 등록 API" 에서 StoryStatus를 DONE으로 바로 저장하도록 변경
> fix : "갤러리 영상 묶음 기록 등록 API" 에서 StoryStatus를 DONE으로 바로 저장하도록 변경

- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/application/CheckUnreadNotificationExist.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/application/DeleteNotification.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/application/GetNotifications.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/application/MarkNotificationRead.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/presentation/NotificationCommandController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/presentation/NotificationQueryController.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/presentation/NotificationResponse.kt
- clog-api/src/main/kotlin/org/depromeet/clog/server/api/notification/presentation/UnreadExistResponse.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ErrorCode.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/notification/NotificationCommand.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/notification/NotificationNotFoundException.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/notification/NotificationQuery.kt
- clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/notification/NotificationRepository.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/NotificationMapper.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/notification/NotificationAdapter.kt
- clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/notification/NotificationJpaRepository.kt
- 최근 30일 이내의 알림을 최신순으로 조회
- 알림 타입 필터로 종류별 알림조회 가능 (FOLLOW : 친구추가 / EVENT : 이벤트 / null : 전체)
- 조회시 모든 새알림표식 삭제
- 새 알림 존재 여부 조회(앱 뱃지와 레드닷 표시에 사용)
- 새 알림이 하나라도 있으면 true, 아니면 false 반환
- 알림 삭제
- 알림 읽음 처리
- 알림탭에서 알림 클릭으로 직접 이동 시 호출
- 읽는 해당 알림에 새알림표식 제거
- #182
> feat : 알림탭 조회/삭제 기능 구현
